version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
    container_name: zookeeper
    network_mode: "host"
    hostname: localhost

  kafka:
    image: wurstmeister/kafka:latest
    ports:
    - "9092:9092"
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_ZOOKEEPER_CONNECT: "localhost:2181"
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
    hostname: localhost
    network_mode: "host"
    depends_on:
     - zookeeper
